control_constants:
  update_rate: 100.0 # [Hz]   publish motor torques with this frequency. every 10ms = 100Hz

  # controller_type:        # "2D","3D","drive", this value is set through launch file!
  # motors_controller_type: # "PositionJointInterface", "VelocityJointInterface", "EffortJointInterface" this value is set through launch file.

  #Control2D Gains:
